### ISSUE TITLE
Test cases do not work consistenly

### ISSUE THREAD

**Issue by ChrisReinke** [ros4hri/pyhri#1]
Running the test cases does not work consistently for me. 
Sometimes some of the subtests work, sometimes they don't.

It seems to be a problem because of the following problem: https://answers.ros.org/question/251194/rospy-subscriber-needs-sleep-some-time-until-the-first-message-is-received/

TLDR:
Sending or receiving messages directly after creating the publisher / subscriber might not work as it is not correctly set up yet.
A rospy.sleep(1) behind creating them is needed for some systems to have it working correctly.

**Comment by ChrisReinke** [comment]
The tests are more stable with the new release 0.1.3.

I still experience sometimes (~1 out 5 times) a problem.

ros@fdfbfc4f61b2:/scratchlocal/creinke/data/study/perception/code/spring/robot_ws/src/pyhri/test$ python test_pyhri.py 
[ROSUNIT] Outputting test results to /home/ros/.ros/test_results/pyhri/rosunit-test_pyhri.xml
[Testcase: test_get_bodies] ... ok
[Testcase: test_get_faces] ... ok
[Testcase: test_get_faces_roi] ... ok
[Testcase: test_get_known_persons] ... ok
[Testcase: test_get_tracked_persons] ... ok
[Testcase: test_get_voices] ... ok
[Testcase: test_person_attributes] ... FAILURE!
FAILURE: unexpectedly None
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "test_pyhri.py", line 317, in test_person_attributes
    self.assertIsNotNone(p1.face)
  File "/usr/lib/python3.8/unittest/case.py", line 1328, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
--------------------------------------------------------------------------------
-------------------------------------------------------------
SUMMARY:
 * RESULT: FAIL
 * TESTS: 7
 * ERRORS: 0 []
 * FAILURES: 1 [test_person_attributes]

**Comment by severin-lemaignan** [comment]
thanks for the feedback. These timing issues are super fiddly, and depends a lot on each ROS machine. I've pushed a new version with a slightly longer delay. Let me know if it fixes the issue for you. Otherwise, please increase the delays in the test file as required on your machine, and create a PR (so that we find a compromise that work on as many ROS configurations as possible).

**Comment by ChrisReinke** [comment]
Works now fine for.
