### ISSUE TITLE
Feature Request: Configuration of subscribed subtopics and custom topics

### ISSUE THREAD

**Issue by ChrisReinke** [ros4hri/pyhri#2]
Currently, the HRIListener subscribes to all required subtopics of bodies, faces, and voices, for example body.roi.
But in many situations, only a subset of these topics is needed.
Thus there should be a mechanism to define with subtopics are listened to.

Moreover, it should be possible to add custom subtopics.

Possible API interface:
```
def my_data_converter_func(data):
     # some function that converts the data in a custom format
     ...
     return converted_data

hri = HRIInterface()
hri.add_body_topic(name='roi', data_type=RegionOfInterest, data_converter=my_data_converter_func)
```

**Comment by severin-lemaignan** [comment]
I'm not in favour of offering such mechanism directly in the library. If you need to transform your data, you can do it in the callback of eg `HRIListener.on_face`.

wrt to only subscribing to some topics: what is your use-case? (eg, why is it an issue for you to subscribe to all the ROS4HRI topics by default?)

**Comment by ChrisReinke** [comment]
I would feel that it could hinder performance if all ros4hri nodes subscribe to all topics of it instead of just the ones they need.

Moreover, such as mechanism would allow to define custom subtopics, for example for the body (e.g. height of the body).
Otherwise, if I have to create again for each tracked body and custom subtopic a subscriber manually (/humans/bodies/<ID>/height) which I hoped the pyhri interface would make easier for me.

**Comment by severin-lemaignan** [comment]
while I understand the value of being able to subscribe to additional subtopics, we need to find a 'nice' API to do so. Your initial proposal does not really help people accessing ROS4HRI topic if they need to manually configure all the topic every time.

We could however have all the basic subtopics (ie, the REP155 ones) available by default and  a method to add additional ones:

But to be honest, it is something you can already do like that:

```python
body = hri.persons['id'].body
body.height = 0
body.height_sub = rospy.Subscriber(body.ns + "/height", Float32, lambda msg: body.height = msg.data) 
```

I am going to close this issue for now. If you still feel that this would be a important feature to have 'by default', please re-open or (better) submit a pull-request.
