### ISSUE TITLE
Bug: hri.known_persons does not update with a new face when a person leaves and returns

### ISSUE THREAD

**Issue by brianjzhang** [ros4hri/pyhri#4]
**Expected Behavior**: when a known person `person` returns to being visible, `person.face` becomes a valid `Face` instead of none.

**Current Behavior**: `person.face` remains `None`. 

**To Replicate**: 
Follow part 1.1 on the [IROS 2022 tutorial](http://wiki.ros.org/hri/Tutorials/ROS4HRI%40IROS22).

Create and run the following script:
```python
#!/usr/bin/env python3

import rospy
from hri import HRIListener

rospy.init_node('hello', anonymous=True)
rate = rospy.Rate(10)
hri = HRIListener()

while not rospy.is_shutdown():
    for id, person in hri.known_persons.items():
    # for id, person in hri.tracked_persons.items():
        if person.face or person.body:
            print("Person %s is seen with some id %s" % (id, person.face.id))
        else:
            print("Person %s is not seen" % id)
    rate.sleep()
```

**Potential Solution**: when running using `hri.tracked_persons.items()` instead of `hri.known_persons.items()`, there is a single tick where `Person person_br is not seen` is the output. This indicates that the person has become tracked, but has yet to be assigned a face. `persons_tracked` seems like it is updated on each tick, so potentially [this callback](https://github.com/ros4hri/pyhri/blob/ccc234be2491c1f37faf9de9351f6e5d7fc16812/src/hri/person.py#L137) is being run before the face list is populated. Unlike `persons_tracked`, `known_persons` may be relying on a one-time call to this callback instead of polling and thus may never get the face. Ensuring that the face (possibly similar for body and voice) list is updated first would solve this problem.

**Comment by severin-lemaignan** [comment]
bug fixed in 0.3.1. Thanks for reporting!
